### ISSUE TITLE
Design Complexity

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#19]
From Martin Thomson

> This design is very complex.  Some of the details in the document probably do not need to be specified in the level of detail provided.  Section 5 for instance describes resources that provide clients with data about other resources, which isn't really consistent with HTTP principles, but they probably aren't necessary either.
> 
> As long as servers adhere to the invariants (S5.5), clients can ask for incremental resources based on what they know and either get a snapshot or increments based on what the server is willing to serve them and what they are willing to process.  The design here requires additional round trips to gather information about the information the client really wants when it could probably ask for a resource, use etags to indicate what it has, use Accept to indicate what it can handle, and the server could then work out what best to serve up.
> 
> A specific problem that this design creates is strong coupling.  The client needs to know about URI structure in order to use the information in the TIPS view.
> 
> Similar comments might apply to managing the set of clients that might want server push (though again, see the first issue).

and..

> Section 5.5 says:
> 
> > Continuity: ns -> ne, anything in between ns and ne also exists 
> > (implies ni ->
>   ni + 1 patch exists), where ns is start-seq and ne is end-seq
> 
> This section might be reduced to saying:
> 
> > A server needs to ensure that any resource state that it makes 
> > available MUST
> be reachable by clients, either directly via a snapshot (that is, relative to 0) or indirectly by requesting an earlier snapshot and a contiguous set of incremental updates.

**Comment by emiapwil** [comment]
We had some discussion on this issue among the authors and discussed this in the ALTO weekly meeting on April 19. It is suggested that we summarize the discussion here, providing visibility to the working group. Currently, there are three options:

1. Stick with the "metadata" information
2. Let the server directly reply to the client about the next update to be fetched, when a client is creating (or reconnecting) to a TIPS view. Then the client fetches further updates by incrementing by 1.
3. Similar to approach 2 but the server piggybacks information about the current available updates and potential shortcuts to the client, basically a compromise of 1 & 2.

**Comment by lkeller19** [comment]
After further discussion, we agreed that providing the metadata is unnecessary for the TIPS protocol. Thus, we will remove the metadata section from the document and, instead, add the capability for the client to request the next recommended edge to consume (option 2 from above), based on the logic described below:

In the current version of the draft, after requesting the TIPS view, the client receives a recommended starting edge in the TIPS view summary. The client SHOULD then consume that edge and construct the future URIs based on the sequential nature. This is what allows for the concurrent transmission of updates in HTTP/2 and HTTP/3 in the long polling case, because the client can request multiple at the same time. 

However, imagine that the client has not polled in a while:
Scenario 1: the client requests the next logical incremental URI, but the server has compacted the queue so it no longer exists. 
Scenario 2: the client hasn't pulled in a long time and thinks it might be better to get a full replacement of the resource. 

In both these scenarios, the client must take the same following action:
Current version w/ full metadata: the client pulls the metadata of the updates graph and calculates the next edge to take (which is presumably the most recent snapshot). The client pulls that edge and then follows the same increment by 1 pattern as before.
New Proposed Version: the client requests for the next edge it should pull based on the version tag of the resource it already has and the server provides it with the recommended next-edge URI. The client then pulls that edge using that URI and constructs the future ones from there, following the same increment by 1 pattern as before.
