### ISSUE TITLE
Ops Considerations

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#23]
From Sheng Jiang

> This document intents for Standards Track. It  document specifies a new ALTO Transport Information Publication Service (TIPS), which takes advantage of HTTP/2 and later versions already support concurrent, non-blocking transport of multiple streams in the same HTTP connection. This document is well-written and READY with minor Nits (below) for publication.
> 
> In section 2.5 "TIPS With HTTP/1.x". This document claims "TIPS
>    still functions with HTTP/1.x for client pull functionality only,
>    with the limitation that it cannot cancel any outstanding requests or
>    fetch resources concurrently over the same connection." However, it is unclear what operations/procedure defined in this document will fail when TIPS work over HTTP/1.x (also whether there are scenarios the server/client have to fall back to HTTP/1.x), the signal or error code the TIPS will provide, and how the server and client should act when these failures happen.
> 
> This looks like an operational hole that authors must fill before publication.
> However, I am not sure, if there is no scenarios that the server/client have to fall back to HTTP/1.x, the authors may simply declare the TIPS SHOULD not work with HTTP/1.x.
>

**Comment by lkeller19** [comment]
Full mailing list response here: https://mailarchive.ietf.org/arch/msg/alto/4kY7J1o1PpBn1gmybppd-4bBfbM/

Proposed change to section 2.5:
OLD
<name>TIPS with HTTP/1.x<name>

<t>While TIPS is designed to take advantage of newer HTTP features, TIPS still functions with HTTP/1.x for client pull functionality only, with the limitation that it cannot cancel any outstanding requests or fetch resources concurrently over the same connection.<t>

NEW
<name>TIPS with Different HTTP Versions<name>

<t>The HTTP version a connection uses is negotiated between client and server based on the respective HTTP RFC documents.</t>

 <t>While TIPS is designed to take advantage of newer HTTP features like server push and substreams for concurrent fetch, TIPS still functions with HTTP/1.x for client pull defined in Section 6, with the limitation that it cannot cancel any outstanding requests or fetch resources concurrently over the same connection due to the blocking nature of HTTP/1.x requests.  Additionally, because HTTP/1.x does not support server push, the use of TIPS with server push defined in Section 7 is not available if a client connects to an ALTO server with HTTP/1.x. If a client only capable of HTTP/1.x desires to monitor multiple resources at the same time, it must open multiple connections, one for each resource. For HTTP/2 and /3, because of substreams, multiple resources can be monitored simultaneously.</t>
